name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: false
        #install: >-
         # mingw-w64-x86_64-gcc
         # make
    - uses: actions/checkout@v4
    - name: make
      run: make gitmake.mk -B
