name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: false
        #install: >-
         # mingw-w64-x86_64-gcc
         # make
    - uses: actions/checkout@v4
    - name: dir1
      run: md bin
    - name: dir2
      run: md lib
    - name: make
      run: make -B
    - name: clean1
      run: del bin\wincppapi.dll
    - name: clean2
      run: del lib\libwincppapi.lib